<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="KubernetesClient" Version="17.0.14" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\protos\background_images.proto" GrpcServices="Both"/>
        <Protobuf Include="..\protos\visitor_insights.proto" GrpcServices="Both" />
        <Protobuf Include="..\protos\send_email_to_admin.proto" GrpcServices="Both" />
        <Protobuf Include="..\protos\k8s_stats.proto" GrpcServices="Both" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Portfolio.Infrastructure\Portfolio.Infrastructure.csproj" />
    </ItemGroup>

</Project>
