global:
  # Automatically load AUTHENTIK_SECRET_KEY, AUTHENTIK_POSTGRESQL__USER and AUTHENTIK_POSTGRESQL__PASSWORD into all pods
  envFrom:
    - secretRef:
        name: authentik-helm-secrets

authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: true
  postgresql:
    # -- set the postgresql hostname to talk to
    # if unset and .Values.postgresql.enabled == true, will generate the default
    # @default -- `{{ .Release.Name }}-postgresql`
    host: "postgres-clusterip.database.svc.cluster.local"
    # -- postgresql Database name
    # @default -- `authentik`
    name: "authentik"
    # -- postgresql Username
    # @default -- `authentik`
    # Got user from secret
    # user: "example-user"
    # -- postgresql password
    # Got password from secret
    # password: "example-password"
    # -- postgresql port
    port: 5432

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - authentik.anil-sezer.com
      - authentik.anilsezer.net
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: "authentik-tls"
        hosts:
          - "authentik.anil-sezer.com"
          - "authentik.anilsezer.net"
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi

worker:
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi

postgresql:
  enabled: false