apiVersion: batch/v1
kind: CronJob
metadata:
  name: terminate-idle-db-connections
spec:
  schedule: "0 * * * *" # Runs every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres
              image: postgres:latest
              env:
                - name: PGPASSWORD
                  value: rgT6%Qk9jTaURwK!&
              command: ["psql"]
              volumes:
                - name: terminate-idle-db-connections-query
                  configMap:
                    name: terminate-idle-db-connections-query-config-map
              args:
                - -U
                - default-user
                - -h
                - postgres-service
                - -d
                - postgres
                - -f
                - /terminate-idle-db-connections-query.sql 
          restartPolicy: Never
