---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-lookup-go
  namespace: portfolio
spec:
  schedule: "*/20 * * * *"  # Runs every 20 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: ip-lookup-go
              image: imgregistry.anil-sezer.com/iplookup-cron-go:latest
              env:
              - name: GRPC_BASE_URL
                value: "grpc.portfolio.svc.cluster.local:8080"

          restartPolicy: Never
