---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - serviceaccount-k8sstats.yml
  - clusterrole-k8sstats.yml
  - clusterrolebinding-k8sstats.yml
  - svc-clusterip.yml
  - deployment.yml
