apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: portfolio-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
