---
- name: Update all packages on rpi
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  register: package_update_result
  become: true

- name: Reboot device
  ansible.builtin.reboot:
    reboot_timeout: 3600
    msg: Rebooting machine in 3600 as timeout
  when: package_update_result.changed
  become: true
