---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-nfs-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: seq-nfs-pv
