---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-nfs
  namespace: image-registry
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.119
    path: /mnt/nas/disk/k8s/image-registry
