---
apiVersion: v1
kind: Service
metadata:
  name: otel-test-svc
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 31390
