---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.119
    path: /mnt/nas/ssd/k8s/uptime
