apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31388
