---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adminer-tls
  namespace: database
spec:
  secretName: adminer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - adminer.anil-sezer.com