---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminneo
  namespace: database
  labels:
    app: adminneo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminneo
  template:
    metadata:
      labels:
        app: adminneo
    spec:
      containers:
        - name: adminneo
          image: adminneoorg/adminneo:latest
          ports:
            - containerPort: 8080
          env:
            - name: NEO_DEFAULT_SERVER
              value: "postgres-clusterip.database.svc.cluster.local"
            - name: NEO_DEFAULT_DRIVER
              value: "pgsql"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 600m
              memory: 512Mi
