---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/pg_ctl", "stop", "-D", "/var/lib/postgresql/data", "-m", "fast" ]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-init-secrets
                  key: SQL_DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-init-secrets
                  key: SQL_DB_PASSWORD

          volumeMounts:
            - name: postgres-nfs-pvc
              mountPath: /var/lib/postgresql/data
              readOnly: false
      volumes:
        - name: postgres-nfs-pvc
          persistentVolumeClaim:
            claimName: postgres-nfs-pvc
