---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-loadbalancer
  namespace: database
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: internal
      protocol: TCP
      port: 5432
      targetPort: 5432
