---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: get-daily-images
  namespace: portfolio
spec:
  schedule: "0 2 * * *"  # Every day at 02:00 (2:00 AM)
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: get-daily-images
              image: imgregistry.anil-sezer.com/get-daily-images-go-cron:latest
              env:
                - name: GRPC_BASE_URL
                  value: "grpc.portfolio.svc.cluster.local:8080"
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: Never
