---
- name: Update all nodes, then set up some quality-of-life tools, then setup Kubernetes cluster
  hosts: kubernetes_nodes
  gather_facts: true
  vars_files:
    - variables.yml
  handlers:
    - name: Reboot device
      ansible.builtin.reboot:
        reboot_timeout: 3600
        msg: Rebooting machine in 3600 as timeout
      when: package_update_result.changed

  tasks:
    # -----------------------
    #  Install Core Components
    # -----------------------
    - name: Fully update Ubuntu
      ansible.builtin.import_tasks: ./os-and-cli-tools/update-ubuntu.yml

    - name: Install some must have components like git, gpg, unzip
      ansible.builtin.import_tasks: ./os-and-cli-tools/install-core-components.yml

    - name: Setting Oh my ZSH
      ansible.builtin.import_tasks: ./os-and-cli-tools/install-oh-my-zsh.yml

    - name: Install Cli tools like dust, batcat, fzf and others
      ansible.builtin.import_tasks: ./os-and-cli-tools/install-cli-tools.yml

    - name: Fully update Ubuntu
      ansible.builtin.import_tasks: ./os-and-cli-tools/update-ubuntu.yml

    - name: Copy some useful scripts, including the backup cron code and shutdown markers
      ansible.builtin.import_tasks: ./stremio/copy-support-scripts.yml

    - name: Setup watchdog
      ansible.builtin.import_tasks: ./hardware-watchdog/enable-watchdog.yml

    - name: Add shutdown markers
      ansible.builtin.import_tasks: ./hardware-watchdog/add-shutdown-markers.yml
    
    # -----------------
    #  Setup Kubernetes!
    # -----------------
    - name: Create local directory for logs
      ansible.builtin.file:
        path: "{{ kubeadm_init_log_dir }}"
        state: directory
      delegate_to: localhost
    
    - name: Disabling swap is a must for Kubernetes
      ansible.builtin.import_tasks: kubernetes-setup/disable-swap.yml
    
    - name: Edit /etc/hosts in preparation for the cluster DNS
      ansible.builtin.import_tasks: kubernetes-setup/edit-etc-host.yml
    
    - name: Install first batch of required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nfs-common
        update_cache: true
        state: present
        install_recommends: true
    
    - name: Enable cgroup_enable & cgroup_memory options for Kubernetes
      ansible.builtin.import_tasks: kubernetes-setup/enable-resource-constraints-on-raspberry-pi.yml
    
    - name: Edit containerd configs so it will behave with kubelet
      ansible.builtin.import_tasks: kubernetes-setup/containerd-config.yml
    
    - name: Enable some required kernel modules for containerd
      ansible.builtin.import_tasks: kubernetes-setup/kernel-modules.yml
    
    - name: Manually enable IPv4 packet forwarding for Kubernetes
      ansible.builtin.import_tasks: kubernetes-setup/ipv4.yml
    
    - name: Install kubeadm, kubectl and kubelet
      ansible.builtin.import_tasks: kubernetes-setup/install-kubeadm-kubectl-kubelet.yml
    
    - name: Let's boot the control plane!
      ansible.builtin.import_tasks: kubernetes-setup/kubeadm-init-control-node.yml
      when: ansible_default_ipv4.address == control_plane_ip
    
    # - name: Lets boot the worker plane(s)!
    #   ansible.builtin.import_tasks: kubernetes-setup/kubeadm-init-worker-nodes.yml
    #   when: ansible_default_ipv4.address != control_plane_ip
    
    - name: Equalize containerd and kubelet sandbox image urls.
      ansible.builtin.import_tasks: kubernetes-setup/equalize-pause-image-for-containerd-and-kubelet.yml
    
    - name: Install Helm
      ansible.builtin.command: snap install helm --classic
    
    - name: Enable hosts plugin at CoreDNS and add node ips there
      ansible.builtin.import_tasks: kubernetes-setup/core-dns-config.yml
    
    - name: Setup MetalLB
      ansible.builtin.import_tasks: kubernetes-setup/setup-metal-lb.yml
    
    # todo: Switch to traefik?
    # https://www.adaltas.com/en/2022/09/08/kubernetes-metallb-nginx/
    - name: Install Nginx
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml
      become: false
    
    - name: Install Cert Manager
      ansible.builtin.import_tasks: kubernetes-setup/install-cert-manager.yml
    
    # - name: Containerd might need a reconfiguration because installing a CNI sometimes alter it.
    #   ansible.builtin.import_tasks: kubernetes-setup/containerd-config.yml

    # TODO: REBOOT AFTER INSTALL, IT FIXES CRASHLOOPBACKOFF
    
    # Add kubectl & kubeadm completion
    # kubectl completion -h
    # kubeadm completion -h
