---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: prometheus-nfs
