---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backups-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.122
    path: /mnt/nas/disk/k8s/db-backups/db-backups/postgres/portfolio