---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backup-portfolio-nfs
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: db-backup-portfolio-nfs
