---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backups-nfs
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: db-backups-nfs-pv
