// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: background_images.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// There is a duplicate for this enum in the proto file. If this file is edited, that should be too. Search this code for it: GXJQJZ
type ImageOfTheDaySource int32

const (
	ImageOfTheDaySource_Bing ImageOfTheDaySource = 0
	ImageOfTheDaySource_NASA ImageOfTheDaySource = 1
	ImageOfTheDaySource_None ImageOfTheDaySource = 2
)

// Enum value maps for ImageOfTheDaySource.
var (
	ImageOfTheDaySource_name = map[int32]string{
		0: "Bing",
		1: "NASA",
		2: "None",
	}
	ImageOfTheDaySource_value = map[string]int32{
		"Bing": 0,
		"NASA": 1,
		"None": 2,
	}
)

func (x ImageOfTheDaySource) Enum() *ImageOfTheDaySource {
	p := new(ImageOfTheDaySource)
	*p = x
	return p
}

func (x ImageOfTheDaySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageOfTheDaySource) Descriptor() protoreflect.EnumDescriptor {
	return file_background_images_proto_enumTypes[0].Descriptor()
}

func (ImageOfTheDaySource) Type() protoreflect.EnumType {
	return &file_background_images_proto_enumTypes[0]
}

func (x ImageOfTheDaySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageOfTheDaySource.Descriptor instead.
func (ImageOfTheDaySource) EnumDescriptor() ([]byte, []int) {
	return file_background_images_proto_rawDescGZIP(), []int{0}
}

type BackgroundImageDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,2,opt,name=altText,proto3" json:"altText,omitempty"`
	Source        ImageOfTheDaySource    `protobuf:"varint,3,opt,name=Source,proto3,enum=background_images.ImageOfTheDaySource" json:"Source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundImageDetails) Reset() {
	*x = BackgroundImageDetails{}
	mi := &file_background_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundImageDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundImageDetails) ProtoMessage() {}

func (x *BackgroundImageDetails) ProtoReflect() protoreflect.Message {
	mi := &file_background_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundImageDetails.ProtoReflect.Descriptor instead.
func (*BackgroundImageDetails) Descriptor() ([]byte, []int) {
	return file_background_images_proto_rawDescGZIP(), []int{0}
}

func (x *BackgroundImageDetails) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackgroundImageDetails) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *BackgroundImageDetails) GetSource() ImageOfTheDaySource {
	if x != nil {
		return x.Source
	}
	return ImageOfTheDaySource_Bing
}

var File_background_images_proto protoreflect.FileDescriptor

const file_background_images_proto_rawDesc = "" +
	"\n" +
	"\x17background_images.proto\x12\x11background_images\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n" +
	"\x16BackgroundImageDetails\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\aaltText\x18\x02 \x01(\tR\aaltText\x12>\n" +
	"\x06Source\x18\x03 \x01(\x0e2&.background_images.ImageOfTheDaySourceR\x06Source*3\n" +
	"\x13ImageOfTheDaySource\x12\b\n" +
	"\x04Bing\x10\x00\x12\b\n" +
	"\x04NASA\x10\x01\x12\b\n" +
	"\x04None\x10\x022\xaa\x01\n" +
	"\x10BackgroundImages\x12L\n" +
	"\aPersist\x12).background_images.BackgroundImageDetails\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a).background_images.BackgroundImageDetailsB\x19Z\x06proto/\xaa\x02\x0ePortfolio.Grpcb\x06proto3"

var (
	file_background_images_proto_rawDescOnce sync.Once
	file_background_images_proto_rawDescData []byte
)

func file_background_images_proto_rawDescGZIP() []byte {
	file_background_images_proto_rawDescOnce.Do(func() {
		file_background_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_background_images_proto_rawDesc), len(file_background_images_proto_rawDesc)))
	})
	return file_background_images_proto_rawDescData
}

var file_background_images_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_background_images_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_background_images_proto_goTypes = []any{
	(ImageOfTheDaySource)(0),       // 0: background_images.ImageOfTheDaySource
	(*BackgroundImageDetails)(nil), // 1: background_images.BackgroundImageDetails
	(*emptypb.Empty)(nil),          // 2: google.protobuf.Empty
}
var file_background_images_proto_depIdxs = []int32{
	0, // 0: background_images.BackgroundImageDetails.Source:type_name -> background_images.ImageOfTheDaySource
	1, // 1: background_images.BackgroundImages.Persist:input_type -> background_images.BackgroundImageDetails
	2, // 2: background_images.BackgroundImages.Get:input_type -> google.protobuf.Empty
	2, // 3: background_images.BackgroundImages.Persist:output_type -> google.protobuf.Empty
	1, // 4: background_images.BackgroundImages.Get:output_type -> background_images.BackgroundImageDetails
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_background_images_proto_init() }
func file_background_images_proto_init() {
	if File_background_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_background_images_proto_rawDesc), len(file_background_images_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_background_images_proto_goTypes,
		DependencyIndexes: file_background_images_proto_depIdxs,
		EnumInfos:         file_background_images_proto_enumTypes,
		MessageInfos:      file_background_images_proto_msgTypes,
	}.Build()
	File_background_images_proto = out.File
	file_background_images_proto_goTypes = nil
	file_background_images_proto_depIdxs = nil
}
