name: Build and Push Docker Image

on:
  push:
    branches:
      - githubBuildAction

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
      - name: Restore dependencies
        run: dotnet restore ShopAndEat.sln
      - name: Build
        run: dotnet build --no-restore ShopAndEat.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal ShopAndEat.sln
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deployment/Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: anilsezer/portfolio:latest